var mongoose              = require('mongoose');

var vendor_profile = {
    youtube                 : String,
    twitter                 : String,
    mobile                  : String,
    altphone                : String,
    landphone               : String,
    addressline1            : String,
    addressline2            : String,
    city                    : String,
    pincode                 : Number,
    state                   : String,
    best_way_to_contact     : String,
    filled_in_by            : String,
    agent_id                : String,
    select_services         : String,
    other_services          : String,
    other_services_location : String,
    select_catering         : [String],
    other_menu              : String,
    menu_pricing            : String,
    select_catering_loc     : String,
    menu_notes              : String,
    other_photo_pack        : String,
    photo_pricing           : String,
    select_photography_loc  : String,
    photo_notes             : String,
    other_video_pack        : String,
    video_pricing           : String,
    select_videography_loc  : String,
    video_notes             : String,
    other_stream_pack       : String,
    stream_pricing          : String,
    select_stream_loc       : String,
    stream_notes            : String,
    other_makeup_pack       : String,
    makeup_pricing          : String,
    select_bridal_makeup_loc: String,
    bridal_notes            : String,
    jewellery_notes         : String,
    bridalwear_notes        : String,
    designer_notes          : String,
    cosmetics_notes         : String,
    cards_notes             : String,
    travel_notes            : String,
    accessories_notes       : String,
    venue_notes             : String,
    gallery_notes           : String,
    account_name            : String,
    bank_name               : String,
    branch                  : String,
    branch_district         : String,
    branch_place            : String,
    branch_pincode          : String,
    account_number          : String,
    ifsc                    : String
};

var vendor_account_schema = new mongoose.Schema({
    oauth_id      : String,
    password      : String,
    created       : { type: Date, default: Date.now },
    vendor_profile: vendor_profile
});

module.exports = mongoose.model('vendor_account', vendor_account_schema);